# Generated by Django 5.2.8 on 2025-11-14 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_etiqueta'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='etiquetas',
            field=models.ManyToManyField(related_name='productos', to='productos.etiqueta'),
        ),
    ]
