# Generated by Django 5.2.8 on 2025-11-14 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_producto_etiquetas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(blank=True, max_length=100)),
                ('tamaño', models.CharField(blank=True, max_length=100)),
                ('peso', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
