# Generated by Django 5.2.8 on 2025-11-14 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0006_detalle'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalle',
            name='producto',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='detalle', to='productos.producto'),
            preserve_default=False,
        ),
    ]
