# Generated by Django 5.2.8 on 2025-11-14 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0007_detalle_producto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalle',
            name='producto',
        ),
    ]
