# Generated by Django 5.2.8 on 2025-11-14 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0008_remove_detalle_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='producto',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='producto', to='productos.detalle'),
            preserve_default=False,
        ),
    ]
