# Generated by Django 5.2.8 on 2025-11-14 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0009_producto_producto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='producto',
            new_name='detalle',
        ),
    ]
