# Generated by Django 5.2.8 on 2025-11-15 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0010_rename_producto_producto_detalle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='detalle',
        ),
        migrations.AddField(
            model_name='detalle',
            name='producto',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='detalle', to='productos.producto'),
            preserve_default=False,
        ),
    ]
